<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Modules\Catalog\Models\Category;
use App\Modules\Catalog\Models\Product;
use Illuminate\Database\Seeder;

/**
 * Seeds 20 demo products across the catalogue's existing image set. Only 8
 * distinct product photos exist in the repo's root `images/` directory
 * (see the README note this seeder ships alongside), so several products
 * intentionally share the same `image_path` filename — upload those 8
 * files as-is to the `products` directory on the `public` disk
 * (storage/app/public/products) and every row here resolves to a real
 * image rather than a broken link.
 */
final class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = collect([
            'Safety & PPE' => 'safety-ppe',
            'Packaging & Shipping' => 'packaging-shipping',
            'Machinery & Equipment' => 'machinery-equipment',
            'Tape & Adhesives' => 'tape-adhesives',
        ])->mapWithKeys(fn (string $slug, string $name): array => [
            $slug => Category::query()->firstOrCreate(['slug' => $slug], ['name' => $name])->id,
        ]);

        $products = [
            [
                'sku' => 'CGW-MACH-001',
                'supplier_part_id' => 'CGW-MACH-001',
                'name' => 'CGW Bench Grinder Machine',
                'description' => 'Heavy-duty bench grinder for general workshop shaping and finishing tasks.',
                'category' => 'machinery-equipment',
                'unspsc_code' => '27112803',
                'unit_of_measure' => 'EA',
                'pack_size' => 1,
                'stock_quantity' => 15,
                'lead_time_days' => 5,
                'list_price' => 449.00,
                'image_path' => 'products/CGW-machine.jpg',
            ],
            [
                'sku' => 'CGW-MACH-002',
                'supplier_part_id' => 'CGW-MACH-002',
                'name' => 'CGW Angle Grinder Machine - Industrial',
                'description' => 'Industrial-grade angle grinder built for continuous workshop use.',
                'category' => 'machinery-equipment',
                'unspsc_code' => '27112803',
                'unit_of_measure' => 'EA',
                'pack_size' => 1,
                'stock_quantity' => 10,
                'lead_time_days' => 7,
                'list_price' => 389.00,
                'image_path' => 'products/CGW-machine.jpg',
            ],
            [
                'sku' => 'CGW-MACH-003',
                'supplier_part_id' => 'CGW-MACH-003',
                'name' => 'CGW Bench Grinder Machine - Heavy Duty',
                'description' => 'Higher-capacity bench grinder variant for extended production runs.',
                'category' => 'machinery-equipment',
                'unspsc_code' => '27112803',
                'unit_of_measure' => 'EA',
                'pack_size' => 1,
                'stock_quantity' => 8,
                'lead_time_days' => 7,
                'list_price' => 529.00,
                'image_path' => 'products/CGW-machine.jpg',
            ],
            [
                'sku' => 'VEST-HV-001',
                'supplier_part_id' => 'VEST-HV-001',
                'name' => 'Dual-Tone High-Vis Safety Vest with Zipper Pockets',
                'description' => 'Dual-tone colour high-visibility safety vest with zipper pockets for on-site tool storage.',
                'category' => 'safety-ppe',
                'unspsc_code' => '46181504',
                'unit_of_measure' => 'EA',
                'pack_size' => 1,
                'stock_quantity' => 120,
                'lead_time_days' => 3,
                'list_price' => 18.50,
                'image_path' => 'products/Dual-Tone-Colour-High-Vis-Safety-Vest-with-Zipper-Pockets.jpg',
            ],
            [
                'sku' => 'VEST-HV-002',
                'supplier_part_id' => 'VEST-HV-002',
                'name' => 'High-Vis Safety Vest - Class 2 (Orange)',
                'description' => 'Class 2 rated high-visibility orange safety vest for roadside and warehouse work.',
                'category' => 'safety-ppe',
                'unspsc_code' => '46181504',
                'unit_of_measure' => 'EA',
                'pack_size' => 1,
                'stock_quantity' => 95,
                'lead_time_days' => 3,
                'list_price' => 15.75,
                'image_path' => 'products/Dual-Tone-Colour-High-Vis-Safety-Vest-with-Zipper-Pockets.jpg',
            ],
            [
                'sku' => 'VEST-HV-003',
                'supplier_part_id' => 'VEST-HV-003',
                'name' => 'High-Vis Safety Vest with Reflective Tape',
                'description' => 'High-visibility safety vest fitted with reflective tape strips for low-light conditions.',
                'category' => 'safety-ppe',
                'unspsc_code' => '46181504',
                'unit_of_measure' => 'EA',
                'pack_size' => 1,
                'stock_quantity' => 80,
                'lead_time_days' => 3,
                'list_price' => 19.90,
                'image_path' => 'products/Dual-Tone-Colour-High-Vis-Safety-Vest-with-Zipper-Pockets.jpg',
            ],
            [
                'sku' => 'GLV-NIT-M-6390',
                'supplier_part_id' => 'QUBE-6390-M',
                'manufacturer_name' => 'Qube',
                'manufacturer_part_id' => '6390',
                'name' => 'Qube Blue Nitrile Medical Examination Gloves - Medium (Box of 100)',
                'description' => 'Powder-free blue nitrile medical examination gloves, box of 100, size medium.',
                'category' => 'safety-ppe',
                'unspsc_code' => '42132203',
                'unit_of_measure' => 'BX',
                'pack_size' => 100,
                'stock_quantity' => 200,
                'lead_time_days' => 4,
                'list_price' => 12.99,
                'image_path' => 'products/Qube-Blue-Nitrile-Medical-Examination-Gloves-Bx-100-6390.jpg',
            ],
            [
                'sku' => 'GLV-NIT-L-6390',
                'supplier_part_id' => 'QUBE-6390-L',
                'manufacturer_name' => 'Qube',
                'manufacturer_part_id' => '6390',
                'name' => 'Qube Blue Nitrile Medical Examination Gloves - Large (Box of 100)',
                'description' => 'Powder-free blue nitrile medical examination gloves, box of 100, size large.',
                'category' => 'safety-ppe',
                'unspsc_code' => '42132203',
                'unit_of_measure' => 'BX',
                'pack_size' => 100,
                'stock_quantity' => 180,
                'lead_time_days' => 4,
                'list_price' => 12.99,
                'image_path' => 'products/Qube-Blue-Nitrile-Medical-Examination-Gloves-Bx-100-6390.jpg',
            ],
            [
                'sku' => 'GLV-NIT-S-6390',
                'supplier_part_id' => 'QUBE-6390-S',
                'manufacturer_name' => 'Qube',
                'manufacturer_part_id' => '6390',
                'name' => 'Qube Blue Nitrile Medical Examination Gloves - Small (Box of 100)',
                'description' => 'Powder-free blue nitrile medical examination gloves, box of 100, size small.',
                'category' => 'safety-ppe',
                'unspsc_code' => '42132203',
                'unit_of_measure' => 'BX',
                'pack_size' => 100,
                'stock_quantity' => 160,
                'lead_time_days' => 4,
                'list_price' => 12.99,
                'image_path' => 'products/Qube-Blue-Nitrile-Medical-Examination-Gloves-Bx-100-6390.jpg',
            ],
            [
                'sku' => 'CHOCK-URE-M',
                'supplier_part_id' => 'CHOCK-URE-M',
                'name' => 'Urethane Wheel Chock - Medium',
                'description' => 'Medium-sized urethane wheel chock for trucks and light commercial vehicles.',
                'category' => 'machinery-equipment',
                'unspsc_code' => '25172504',
                'unit_of_measure' => 'EA',
                'pack_size' => 1,
                'stock_quantity' => 60,
                'lead_time_days' => 6,
                'list_price' => 34.00,
                'image_path' => 'products/Urethane-wheel-chock-medium.png',
            ],
            [
                'sku' => 'CHOCK-URE-L',
                'supplier_part_id' => 'CHOCK-URE-L',
                'name' => 'Urethane Wheel Chock - Large',
                'description' => 'Large urethane wheel chock rated for heavy trucks and trailers.',
                'category' => 'machinery-equipment',
                'unspsc_code' => '25172504',
                'unit_of_measure' => 'EA',
                'pack_size' => 1,
                'stock_quantity' => 45,
                'lead_time_days' => 6,
                'list_price' => 42.00,
                'image_path' => 'products/Urethane-wheel-chock-medium.png',
            ],
            [
                'sku' => 'CHOCK-URE-S',
                'supplier_part_id' => 'CHOCK-URE-S',
                'name' => 'Urethane Wheel Chock - Small',
                'description' => 'Compact urethane wheel chock suited to passenger vehicles and forklifts.',
                'category' => 'machinery-equipment',
                'unspsc_code' => '25172504',
                'unit_of_measure' => 'EA',
                'pack_size' => 1,
                'stock_quantity' => 70,
                'lead_time_days' => 6,
                'list_price' => 27.50,
                'image_path' => 'products/Urethane-wheel-chock-medium.png',
            ],
            [
                'sku' => 'TAPE-WHT-001',
                'supplier_part_id' => 'TAPE-WHT-001',
                'name' => 'White Packaging Tape',
                'description' => 'General-purpose white packaging tape for carton sealing.',
                'category' => 'tape-adhesives',
                'unspsc_code' => '31201610',
                'unit_of_measure' => 'RL',
                'pack_size' => 6,
                'stock_quantity' => 300,
                'lead_time_days' => 2,
                'list_price' => 22.00,
                'image_path' => 'products/White-Tape.png',
            ],
            [
                'sku' => 'TAPE-WHT-002',
                'supplier_part_id' => 'TAPE-WHT-002',
                'name' => 'White Packaging Tape - Heavy Duty',
                'description' => 'Heavy-duty white packaging tape for reinforced carton sealing.',
                'category' => 'tape-adhesives',
                'unspsc_code' => '31201610',
                'unit_of_measure' => 'RL',
                'pack_size' => 6,
                'stock_quantity' => 250,
                'lead_time_days' => 2,
                'list_price' => 26.50,
                'image_path' => 'products/White-Tape.png',
            ],
            [
                'sku' => 'TAPE-BOPP-001',
                'supplier_part_id' => 'TAPE-BOPP-001',
                'name' => 'BOPP Tape - Regular',
                'description' => 'Regular-grade BOPP tape for everyday carton sealing and bundling.',
                'category' => 'tape-adhesives',
                'unspsc_code' => '31201610',
                'unit_of_measure' => 'RL',
                'pack_size' => 6,
                'stock_quantity' => 320,
                'lead_time_days' => 2,
                'list_price' => 19.00,
                'image_path' => 'products/bopp tape regular.jpg',
            ],
            [
                'sku' => 'TAPE-BOPP-002',
                'supplier_part_id' => 'TAPE-BOPP-002',
                'name' => 'BOPP Tape - Heavy Duty',
                'description' => 'Heavy-duty BOPP tape with higher tensile strength for palletised loads.',
                'category' => 'tape-adhesives',
                'unspsc_code' => '31201610',
                'unit_of_measure' => 'RL',
                'pack_size' => 6,
                'stock_quantity' => 210,
                'lead_time_days' => 2,
                'list_price' => 23.50,
                'image_path' => 'products/bopp tape regular.jpg',
            ],
            [
                'sku' => 'BAG-PPR-2L',
                'supplier_part_id' => 'BAG-PPR-2L',
                'name' => 'Paper Bags - 2 Litre',
                'description' => 'Kraft paper bags, 2 litre capacity, for retail and food packaging.',
                'category' => 'packaging-shipping',
                'unspsc_code' => '24111503',
                'unit_of_measure' => 'PK',
                'pack_size' => 500,
                'stock_quantity' => 40,
                'lead_time_days' => 5,
                'list_price' => 58.00,
                'image_path' => 'products/paper bags 2 liter.webp',
            ],
            [
                'sku' => 'BAG-PPR-5L',
                'supplier_part_id' => 'BAG-PPR-5L',
                'name' => 'Paper Bags - 5 Litre',
                'description' => 'Kraft paper bags, 5 litre capacity, for retail and food packaging.',
                'category' => 'packaging-shipping',
                'unspsc_code' => '24111503',
                'unit_of_measure' => 'PK',
                'pack_size' => 500,
                'stock_quantity' => 35,
                'lead_time_days' => 5,
                'list_price' => 72.00,
                'image_path' => 'products/paper bags 2 liter.webp',
            ],
            [
                'sku' => 'MAIL-POLY-001',
                'supplier_part_id' => 'MAIL-POLY-001',
                'name' => 'Poly Mailers',
                'description' => 'Self-sealing polyethylene mailers for e-commerce shipping.',
                'category' => 'packaging-shipping',
                'unspsc_code' => '24111503',
                'unit_of_measure' => 'PK',
                'pack_size' => 250,
                'stock_quantity' => 90,
                'lead_time_days' => 4,
                'list_price' => 34.50,
                'image_path' => 'products/poli mailers.jpg',
            ],
            [
                'sku' => 'MAIL-POLY-002',
                'supplier_part_id' => 'MAIL-POLY-002',
                'name' => 'Poly Mailers - Extra Large',
                'description' => 'Extra-large self-sealing polyethylene mailers for bulkier e-commerce shipments.',
                'category' => 'packaging-shipping',
                'unspsc_code' => '24111503',
                'unit_of_measure' => 'PK',
                'pack_size' => 250,
                'stock_quantity' => 65,
                'lead_time_days' => 4,
                'list_price' => 42.00,
                'image_path' => 'products/poli mailers.jpg',
            ],
        ];

        foreach ($products as $product) {
            Product::query()->updateOrCreate(
                ['sku' => $product['sku']],
                [
                    'supplier_part_id' => $product['supplier_part_id'],
                    'supplier_part_auxiliary_id' => null,
                    'manufacturer_part_id' => $product['manufacturer_part_id'] ?? null,
                    'manufacturer_name' => $product['manufacturer_name'] ?? null,
                    'name' => $product['name'],
                    'description' => $product['description'],
                    'long_description' => null,
                    'category_id' => $categories[$product['category']],
                    'unspsc_code' => $product['unspsc_code'],
                    'unit_of_measure' => $product['unit_of_measure'],
                    'pack_size' => $product['pack_size'],
                    'stock_quantity' => $product['stock_quantity'],
                    'lead_time_days' => $product['lead_time_days'],
                    'list_price' => $product['list_price'],
                    'currency' => 'AUD',
                    'image_path' => $product['image_path'],
                    'is_active' => true,
                ],
            );
        }
    }
}
